( function( $ ) {
    app.Row = Backbone.Model.extend({
      defaults:{
        rowID: 'ulpb_Row'+Math.floor((Math.random() * 200000) + 100),
        rowHeight: 100,
        rowHeightUnit:'px',
        rowHeightTablet: '',
        rowHeightUnitTablet:'',
        rowHeightMobile: '',
        rowHeightUnitMobile:'',
        columns: 1,
        columnsDivRule:'none',
        rowData: {
          rowCustomClass:'',
          bg_color: '#fff',
          bg_img: ' ',
          margin: {
            rowMarginTop: 0,
            rowMarginBottom: 0,
            rowMarginLeft: 0,
            rowMarginRight: 0,
          },
          marginTablet:{
            rMTT:'',
            rMBT:'',
            rMLT:'',
            rMRT:'',
          },
          marginMobile:{
            rMTM:'',
            rMBM:'',
            rMLM:'',
            rMRM:'',
          },
          padding:{
            rowPaddingTop: 0,
            rowPaddingBottom: 0,
            rowPaddingLeft: 0,
            rowPaddingRight: 0,
          },
          paddingTablet:{
            rPTT:'',
            rPBT:'',
            rPLT:'',
            rPRT:'',
          },
          paddingMobile:{
            rPTM:'',
            rPBM:'',
            rPLM:'',
            rPRM:'',
          },
          video:{
            rowBgVideoEnable: 'false',
            rowBgVideoLoop: 'loop',
            rowVideoMpfour: ' ',
            rowVideoWebM: ' ',
            rowVideoThumb: ' ',
          },
          customStyling: '',
          customJS: ' ',
          rowBackgroundType:'solid',
          rowGradient:{
            rowGradientColorFirst: '#dd9933',
            rowGradientLocationFirst:'55',
            rowGradientColorSecond:'#eeee22',
            rowGradientLocationSecond:'50',
            rowGradientType:'linear',
            rowGradientPosition:'top left',
            rowGradientAngle:'135',
          },
          rowHoverOptions: {
            rowBgColorHover:'',
            rowBackgroundTypeHover:'',
            rowHoverTransitionDuration:'',
            rowGradientHover:{
              rowGradientColorFirstHover: '',
              rowGradientLocationFirstHover:'',
              rowGradientColorSecondHover:'',
              rowGradientLocationSecondHover:'',
              rowGradientTypeHover:'linear',
              rowGradientPositionHover:'top left',
              rowGradientAngleHover:'',
            }
          },
          rowHideOnDesktop:'',
          rowHideOnTablet:'',
          rowHideOnMobile:'',
        },
        column1: {
          colWidgets: [],
          columnOptions:{
          bg_color: 'transparent',
          margin: {
            columnMarginTop: 0,
            columnMarginBottom: 0,
            columnMarginLeft: 0,
            columnMarginRight: 0,
          },
          padding:{
            columnPaddingTop: 0,
            columnPaddingBottom: 0,
            columnPaddingLeft: 0,
            columnPaddingRight: 0,
          },
          paddingTablet:{
            rPTT:'',
            rPBT:'',
            rPLT:'',
            rPRT:'',
          },
          paddingMobile:{
            rPTM:'',
            rPBM:'',
            rPLM:'',
            rPRM:'',
          },
          marginTablet:{
            rMTT:'',
            rMBT:'',
            rMLT:'',
            rMRT:'',
          },
          marginMobile:{
            rMTM:'',
            rMBM:'',
            rMLM:'',
            rMRM:'',
          },
          width: '',
          widthTablet: '',
          widthMobile: '',
          columnCSS:'/* Add column custom styling here */',
          columnCustomClass:'',
          colHideOnDesktop:'',
          colHideOnTablet:'',
          colHideOnMobile:'',
          colBoxShadow: {
            colBoxShadowH:'',
            colBoxShadowV:'',
            colBoxShadowBlur:'',
            colBoxShadowColor:'',
          },
          colBgImg:'',
          colBackgroundType:'solid',
          colGradient:{
            colGradientColorFirst: '#dd9933',
            colGradientLocationFirst:'55',
            colGradientColorSecond:'#eeee22',
            colGradientLocationSecond:'50',
            colGradientType:'linear',
            colGradientPosition:'top left',
            colGradientAngle:'135',
          },
          colHoverOptions: {
            colBgColorHover:'',
            colBackgroundTypeHover:'',
            colHoverTransitionDuration:'',
            colGradientHover:{
              colGradientColorFirstHover: '',
              colGradientLocationFirstHover:'',
              colGradientColorSecondHover:'',
              colGradientLocationSecondHover:'',
              colGradientTypeHover:'linear',
              colGradientPositionHover:'top left',
              colGradientAngleHover:'',
            },
          },
          }
        },
        column2: {
          colWidgets: [],
          columnOptions:{
          bg_color: 'transparent',
          margin: {
            columnMarginTop: 0,
            columnMarginBottom: 0,
            columnMarginLeft: 0,
            columnMarginRight: 0,
          },
          padding:{
            columnPaddingTop: 0,
            columnPaddingBottom: 0,
            columnPaddingLeft: 0,
            columnPaddingRight: 0,
          },
          paddingTablet:{
            rPTT:'',
            rPBT:'',
            rPLT:'',
            rPRT:'',
          },
          paddingMobile:{
            rPTM:'',
            rPBM:'',
            rPLM:'',
            rPRM:'',
          },
          marginTablet:{
            rMTT:'',
            rMBT:'',
            rMLT:'',
            rMRT:'',
          },
          marginMobile:{
            rMTM:'',
            rMBM:'',
            rMLM:'',
            rMRM:'',
          },
          width: '',
          widthTablet: '',
          widthMobile: '',
          columnCSS:'/* Add column custom styling here */',
          columnCustomClass:'',
          colHideOnDesktop:'',
          colHideOnTablet:'',
          colHideOnMobile:'',
          colBoxShadow: {
            colBoxShadowH:'',
            colBoxShadowV:'',
            colBoxShadowBlur:'',
            colBoxShadowColor:'',
          },
          colBgImg:'',
          colBackgroundType:'solid',
          colGradient:{
            colGradientColorFirst: '#dd9933',
            colGradientLocationFirst:'55',
            colGradientColorSecond:'#eeee22',
            colGradientLocationSecond:'50',
            colGradientType:'linear',
            colGradientPosition:'top left',
            colGradientAngle:'135',
          },
          colHoverOptions: {
            colBgColorHover:'',
            colBackgroundTypeHover:'',
            colHoverTransitionDuration:'',
            colGradientHover:{
              colGradientColorFirstHover: '',
              colGradientLocationFirstHover:'',
              colGradientColorSecondHover:'',
              colGradientLocationSecondHover:'',
              colGradientTypeHover:'linear',
              colGradientPositionHover:'top left',
              colGradientAngleHover:'',
            },
          },
          }
        },
        column3: {
          colWidgets: [],
          columnOptions:{
          bg_color: 'transparent',
          margin: {
            columnMarginTop: 0,
            columnMarginBottom: 0,
            columnMarginLeft: 0,
            columnMarginRight: 0,
          },
          padding:{
            columnPaddingTop: 0,
            columnPaddingBottom: 0,
            columnPaddingLeft: 0,
            columnPaddingRight: 0,
          },
          paddingTablet:{
            rPTT:'',
            rPBT:'',
            rPLT:'',
            rPRT:'',
          },
          paddingMobile:{
            rPTM:'',
            rPBM:'',
            rPLM:'',
            rPRM:'',
          },
          marginTablet:{
            rMTT:'',
            rMBT:'',
            rMLT:'',
            rMRT:'',
          },
          marginMobile:{
            rMTM:'',
            rMBM:'',
            rMLM:'',
            rMRM:'',
          },
          width: '',
          widthTablet: '',
          widthMobile: '',
          columnCSS:'/* Add column custom styling here */',
          columnCustomClass:'',
          colHideOnDesktop:'',
          colHideOnTablet:'',
          colHideOnMobile:'',
          colBoxShadow: {
            colBoxShadowH:'',
            colBoxShadowV:'',
            colBoxShadowBlur:'',
            colBoxShadowColor:'',
          },
          colBgImg:'',
          colBackgroundType:'solid',
          colGradient:{
            colGradientColorFirst: '#dd9933',
            colGradientLocationFirst:'55',
            colGradientColorSecond:'#eeee22',
            colGradientLocationSecond:'50',
            colGradientType:'linear',
            colGradientPosition:'top left',
            colGradientAngle:'135',
          },
          colHoverOptions: {
            colBgColorHover:'',
            colBackgroundTypeHover:'',
            colHoverTransitionDuration:'',
            colGradientHover:{
              colGradientColorFirstHover: '',
              colGradientLocationFirstHover:'',
              colGradientColorSecondHover:'',
              colGradientLocationSecondHover:'',
              colGradientTypeHover:'linear',
              colGradientPositionHover:'top left',
              colGradientAngleHover:'',
            },
          },
          }
        },
        column4: {
          colWidgets: [],
          columnOptions:{
          bg_color: 'transparent',
          margin: {
            columnMarginTop: 0,
            columnMarginBottom: 0,
            columnMarginLeft: 0,
            columnMarginRight: 0,
          },
          padding:{
            columnPaddingTop: 0,
            columnPaddingBottom: 0,
            columnPaddingLeft: 0,
            columnPaddingRight: 0,
          },
          paddingTablet:{
            rPTT:'',
            rPBT:'',
            rPLT:'',
            rPRT:'',
          },
          paddingMobile:{
            rPTM:'',
            rPBM:'',
            rPLM:'',
            rPRM:'',
          },
          marginTablet:{
            rMTT:'',
            rMBT:'',
            rMLT:'',
            rMRT:'',
          },
          marginMobile:{
            rMTM:'',
            rMBM:'',
            rMLM:'',
            rMRM:'',
          },
          width: '',
          widthTablet: '',
          widthMobile: '',
          columnCSS:'/* Add column custom styling here */',
          columnCustomClass:'',
          colHideOnDesktop:'',
          colHideOnTablet:'',
          colHideOnMobile:'',
          colBoxShadow: {
            colBoxShadowH:'',
            colBoxShadowV:'',
            colBoxShadowBlur:'',
            colBoxShadowColor:'',
          },
          colBgImg:'',
          colBackgroundType:'solid',
          colGradient:{
            colGradientColorFirst: '#dd9933',
            colGradientLocationFirst:'55',
            colGradientColorSecond:'#eeee22',
            colGradientLocationSecond:'50',
            colGradientType:'linear',
            colGradientPosition:'top left',
            colGradientAngle:'135',
          },
          colHoverOptions: {
            colBgColorHover:'',
            colBackgroundTypeHover:'',
            colHoverTransitionDuration:'',
            colGradientHover:{
              colGradientColorFirstHover: '',
              colGradientLocationFirstHover:'',
              colGradientColorSecondHover:'',
              colGradientLocationSecondHover:'',
              colGradientTypeHover:'linear',
              colGradientPositionHover:'top left',
              colGradientAngleHover:'',
            },
          },
          }
        },
        column5: {
          colWidgets: [],
          columnOptions:{
          bg_color: 'transparent',
          margin: {
            columnMarginTop: 0,
            columnMarginBottom: 0,
            columnMarginLeft: 0,
            columnMarginRight: 0,
          },
          padding:{
            columnPaddingTop: 0,
            columnPaddingBottom: 0,
            columnPaddingLeft: 0,
            columnPaddingRight: 0,
          },
          paddingTablet:{
            rPTT:'',
            rPBT:'',
            rPLT:'',
            rPRT:'',
          },
          paddingMobile:{
            rPTM:'',
            rPBM:'',
            rPLM:'',
            rPRM:'',
          },
          marginTablet:{
            rMTT:'',
            rMBT:'',
            rMLT:'',
            rMRT:'',
          },
          marginMobile:{
            rMTM:'',
            rMBM:'',
            rMLM:'',
            rMRM:'',
          },
          width: '',
          widthTablet: '',
          widthMobile: '',
          columnCSS:'/* Add column custom styling here */',
          columnCustomClass:'',
          colHideOnDesktop:'',
          colHideOnTablet:'',
          colHideOnMobile:'',
          colBoxShadow: {
            colBoxShadowH:'',
            colBoxShadowV:'',
            colBoxShadowBlur:'',
            colBoxShadowColor:'',
          },
          colBgImg:'',
          colBackgroundType:'solid',
          colGradient:{
            colGradientColorFirst: '#dd9933',
            colGradientLocationFirst:'55',
            colGradientColorSecond:'#eeee22',
            colGradientLocationSecond:'50',
            colGradientType:'linear',
            colGradientPosition:'top left',
            colGradientAngle:'135',
          },
          colHoverOptions: {
            colBgColorHover:'',
            colBackgroundTypeHover:'',
            colHoverTransitionDuration:'',
            colGradientHover:{
              colGradientColorFirstHover: '',
              colGradientLocationFirstHover:'',
              colGradientColorSecondHover:'',
              colGradientLocationSecondHover:'',
              colGradientTypeHover:'linear',
              colGradientPositionHover:'top left',
              colGradientAngleHover:'',
            },
          },
          }
        },
        column6: {
          colWidgets: [],
          columnOptions:{
          bg_color: 'transparent',
          margin: {
            columnMarginTop: 0,
            columnMarginBottom: 0,
            columnMarginLeft: 0,
            columnMarginRight: 0,
          },
          padding:{
            columnPaddingTop: 0,
            columnPaddingBottom: 0,
            columnPaddingLeft: 0,
            columnPaddingRight: 0,
          },
          paddingTablet:{
            rPTT:'',
            rPBT:'',
            rPLT:'',
            rPRT:'',
          },
          paddingMobile:{
            rPTM:'',
            rPBM:'',
            rPLM:'',
            rPRM:'',
          },
          marginTablet:{
            rMTT:'',
            rMBT:'',
            rMLT:'',
            rMRT:'',
          },
          marginMobile:{
            rMTM:'',
            rMBM:'',
            rMLM:'',
            rMRM:'',
          },
          width: '',
          widthTablet: '',
          widthMobile: '',
          columnCSS:'/* Add column custom styling here */',
          columnCustomClass:'',
          colHideOnDesktop:'',
          colHideOnTablet:'',
          colHideOnMobile:'',
          colBoxShadow: {
            colBoxShadowH:'',
            colBoxShadowV:'',
            colBoxShadowBlur:'',
            colBoxShadowColor:'',
          },
          colBgImg:'',
          colBackgroundType:'solid',
          colGradient:{
            colGradientColorFirst: '#dd9933',
            colGradientLocationFirst:'55',
            colGradientColorSecond:'#eeee22',
            colGradientLocationSecond:'50',
            colGradientType:'linear',
            colGradientPosition:'top left',
            colGradientAngle:'135',
          },
          colHoverOptions: {
            colBgColorHover:'',
            colBackgroundTypeHover:'',
            colHoverTransitionDuration:'',
            colGradientHover:{
              colGradientColorFirstHover: '',
              colGradientLocationFirstHover:'',
              colGradientColorSecondHover:'',
              colGradientLocationSecondHover:'',
              colGradientTypeHover:'linear',
              colGradientPositionHover:'top left',
              colGradientAngleHover:'',
            },
          },
          }
        },
        column7: {
          colWidgets: [],
          columnOptions:{
          bg_color: 'transparent',
          margin: {
            columnMarginTop: 0,
            columnMarginBottom: 0,
            columnMarginLeft: 0,
            columnMarginRight: 0,
          },
          padding:{
            columnPaddingTop: 0,
            columnPaddingBottom: 0,
            columnPaddingLeft: 0,
            columnPaddingRight: 0,
          },
          paddingTablet:{
            rPTT:'',
            rPBT:'',
            rPLT:'',
            rPRT:'',
          },
          paddingMobile:{
            rPTM:'',
            rPBM:'',
            rPLM:'',
            rPRM:'',
          },
          marginTablet:{
            rMTT:'',
            rMBT:'',
            rMLT:'',
            rMRT:'',
          },
          marginMobile:{
            rMTM:'',
            rMBM:'',
            rMLM:'',
            rMRM:'',
          },
          width: '',
          widthTablet: '',
          widthMobile: '',
          columnCSS:'/* Add column custom styling here */',
          columnCustomClass:'',
          colHideOnDesktop:'',
          colHideOnTablet:'',
          colHideOnMobile:'',
          colBoxShadow: {
            colBoxShadowH:'',
            colBoxShadowV:'',
            colBoxShadowBlur:'',
            colBoxShadowColor:'',
          },
          colBgImg:'',
          colBackgroundType:'solid',
          colGradient:{
            colGradientColorFirst: '#dd9933',
            colGradientLocationFirst:'55',
            colGradientColorSecond:'#eeee22',
            colGradientLocationSecond:'50',
            colGradientType:'linear',
            colGradientPosition:'top left',
            colGradientAngle:'135',
          },
          colHoverOptions: {
            colBgColorHover:'',
            colBackgroundTypeHover:'',
            colHoverTransitionDuration:'',
            colGradientHover:{
              colGradientColorFirstHover: '',
              colGradientLocationFirstHover:'',
              colGradientColorSecondHover:'',
              colGradientLocationSecondHover:'',
              colGradientTypeHover:'linear',
              colGradientPositionHover:'top left',
              colGradientAngleHover:'',
            },
          },
          }
        },
        column8: {
          colWidgets: [],
          columnOptions:{
          bg_color: 'transparent',
          margin: {
            columnMarginTop: 0,
            columnMarginBottom: 0,
            columnMarginLeft: 0,
            columnMarginRight: 0,
          },
          padding:{
            columnPaddingTop: 0,
            columnPaddingBottom: 0,
            columnPaddingLeft: 0,
            columnPaddingRight: 0,
          },
          paddingTablet:{
            rPTT:'',
            rPBT:'',
            rPLT:'',
            rPRT:'',
          },
          paddingMobile:{
            rPTM:'',
            rPBM:'',
            rPLM:'',
            rPRM:'',
          },
          marginTablet:{
            rMTT:'',
            rMBT:'',
            rMLT:'',
            rMRT:'',
          },
          marginMobile:{
            rMTM:'',
            rMBM:'',
            rMLM:'',
            rMRM:'',
          },
          width: '',
          widthTablet: '',
          widthMobile: '',
          columnCSS:'/* Add column custom styling here */',
          columnCustomClass:'',
          colHideOnDesktop:'',
          colHideOnTablet:'',
          colHideOnMobile:'',
          colBoxShadow: {
            colBoxShadowH:'',
            colBoxShadowV:'',
            colBoxShadowBlur:'',
            colBoxShadowColor:'',
          },
          colBgImg:'',
          colBackgroundType:'solid',
          colGradient:{
            colGradientColorFirst: '#dd9933',
            colGradientLocationFirst:'55',
            colGradientColorSecond:'#eeee22',
            colGradientLocationSecond:'50',
            colGradientType:'linear',
            colGradientPosition:'top left',
            colGradientAngle:'135',
          },
          colHoverOptions: {
            colBgColorHover:'',
            colBackgroundTypeHover:'',
            colHoverTransitionDuration:'',
            colGradientHover:{
              colGradientColorFirstHover: '',
              colGradientLocationFirstHover:'',
              colGradientColorSecondHover:'',
              colGradientLocationSecondHover:'',
              colGradientTypeHover:'linear',
              colGradientPositionHover:'top left',
              colGradientAngleHover:'',
            },
          },
          }
        }
      },
      url: "/"
    });
/*
app.Column = Backbone.Model.extend({
  defaults: {
      colWidgets: [],
      columnOptions:{
      bg_color: 'transparent',
      margin: {
        columnMarginTop: 0,
        columnMarginBottom: 0,
        columnMarginLeft: 0,
        columnMarginRight: 0,
        },
      padding:{
        columnPaddingTop: 0,
        columnPaddingBottom: 0,
        columnPaddingLeft: 0,
        columnPaddingRight: 0,
      },
      width: '',
      widthTablet: '',
          widthMobile: '',
      }
  }
});
*/

}( jQuery ) );